### ISSUE TITLE
PyHEP 2024 "proceedings" - tag/release for Zenodo

### ISSUE THREAD

**Issue by eduardo-rodrigues** [Saransh-cpp/PyHEP24-vector-sympy-backend#1]
This refers to https://indico.cern.ch/event/1384010/page/32779-proceedings:

Hello, could you prepare a tag/release of this repo you used for your PyHEP 2024 presentation so that I then mint a DOI on Zenodo, to be citable? Talks are trivial but for repositories a tag is a requirement for the minting.

You can see last year's example at https://zenodo.org/communities/pyhep2023/.

Let me know when done and I will take care of the rest. Advance thanks.

**Comment by Saransh-cpp** [comment]
Hi @eduardo-rodrigues, I have created a release in the repository. Please let me know if anything else is required from my end. Thanks!

**Comment by eduardo-rodrigues** [comment]
Hi. That's all good, thanks again.
